title: Cloud Native Data Platform
baseurl: https://appscode-v3-hugo.web.app
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  domain_appscode: https://appscode-v3-hugo.web.app
  domain_guard: https://kubeguard.dev
  domain_configsyncer: https://config-syncer.com
  domain_gateway: https://gateway.voyagermesh.com
  domain_voyagermesh: https://voyagermesh-v1-hugo.web.app
  domain_stash: https://stashed-v1-hugo.web.app
  domain_kubestash: https://kubestash.com
  domain_kubedb: https://kubedb-v2-hugo.web.app
  domain_kubevault: https://kubevault-v1-hugo.web.app
  domain_kubeform: https://kubeform-v1-hugo.web.app
  domain_pharmer: https://pharmer-v1-hugo.web.app
  domain_kubeci: https://kubeci-v1-hugo.web.app
  domain_kubeshield: https://kubeshield-v1-hugo.web.app
  domain_bytebuilders: https://appscode.com
  domain_marketplace: https://marketplace.appscode.com
  search_engine_ID: 015199383701854252104:jccvu4eiulw
  search_api_key: AIzaSyBrcwLTnL09geNrFMUx1kpL--dT1379aag
  blog_url: https://blog.appscode.com
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
markup:
  goldmark:
    renderer:
      unsafe: true
