title: The Kubernetes Company
baseurl: https://appscode-v3-hugo.web.app
languageCode: en-us
assetDir: static
disableKinds:
  - taxonomy
  - taxonomyTerm
params:
  domain_appscode: http://localhost:1313
  domain_kubedb: https://kubedb-v2-hugo.web.app
  domain_kubevault: https://kubevault-v1-hugo.web.app
  domain_kubeci: https://kubeci-v1-hugo.web.app
  domain_kubeshield: https://kubeshield-v1-hugo.web.app
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_engine_ID: "015199383701854252104:jccvu4eiulw"
  search_api_key: "AIzaSyBo15AW3hatf4fO8actJUZ_d5qZJpx0rXM"
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
menu:
  main:
    - name: "Database"
      identifier: database
      weight: 15
      url: https://kubedb.com/docs/latest/setup/install/
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: Elasticsearch
      identifier: elasticsearch
      parent: database
      weight: 10
    - name: Memcached
      identifier: memcached
      parent: database
      weight: 20
    - name: MongoDB
      identifier: mongodb
      parent: database
      weight: 30
    - name: MySQL
      identifier: mysql
      parent: database
      weight: 40
    - name: PostgreSQL
      identifier: postgres
      parent: database
      weight: 50
    - name: Redis
      identifier: redis
      parent: database
      weight: 60
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_guard:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_kubed:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_searchlight:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_service-broker:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_stash:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_swift:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_voyager:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
  product_pharmer:
    - name: "Documentation"
      weight: 20
    - name: "Community"
      identifier: community
      weight: 25
    - name: GitHub
      identifier: github
      parent: community
      url: "https://github.com/kubedb"
      weight: 3
    - name: Twitter
      identifier: twitter
      parent: community
      url: "https://twitter.com/KubeDB"
      weight: 4
    - name: Groups
      identifier: groups
      parent: community
      url: "https://groups.google.com/forum/#!forum/kubedb"
      weight: 5
    - name: Slack
      identifier: slack
      parent: community
      url: "http://slack.kubernetes.io/"
      weight: 6
    - name: Forum
      identifier: forum
      parent: community
      url: "http://discourse.appscode.com"
      weight: 7
